### PR TITLE
Assorted updates and additions

### PR DESCRIPTION
**Pull request by ghost**
The base repository has not been updated for nearly a year now, so I updated the existing apps and added some new ones.

### CODE REVIEW

**Review by AnnsAnns — CHANGES_REQUESTED** [review]
I like updating it but adding new stuff that isn't essential will mean that this needs to be maintained more and have all the proper licenses.

**Comment by ghost** [comment]
I updated the licenses.

**Comment by nicholemattera** [comment]
Also (at least with the Switch version of Kosmos) we get permission from all the authors as well to include their projects into our bundle. Not sure if Tom did the same originally with this as it was his project.

**Comment by nicholemattera** [comment]
Oh... Github auto closed this. I'm going to move the builder script that we have for the Switch version over to here so we don't store binaries in the repo.

**Pull request closed without merging**
